src/objects/Answer__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Answers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Answers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Answers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Answer</label>
    <nameField>
        <label>Answer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>ProductGroup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ProductGroup</label>
        <referenceTo>ProductGroup__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/ProductGroup__c.object
<CustomObject>
    <label>ProductGroup</label>
    <nameField>
        <label>ProductGroupName</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ProductGroups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Question__c.object
<CustomObject>
    <fields>
        <fullName>ProductGroup__c</fullName>
        <label>ProductGroup</label>
        <referenceTo>ProductGroup__c</referenceTo>
        <relationshipLabel>Questions</relationshipLabel>
        <relationshipName>Questions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>QuestionText__c</fullName>
        <label>QuestionText</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>QuestionType__c</fullName>
        <label>QuestionType</label>
        <picklist>
            <picklistValues>
                <fullName>Text</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Boolean</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Picklist</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TBN_TestcodeforCaptureAnswers.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class TBN_TestcodeforCaptureAnswers {

    static testMethod void myUnitTest() 
    {
         Opportunity  objOpp = new Opportunity ();
         objOpp.Name = 'Opportunity1';
         objOpp.StageName='Stage 0: Unqualified / Inactive';
         objOpp.CloseDate=system.today();
         Insert objOpp;
         
        Opportunity opp= new Opportunity(Name='testOpp', StageName='Prospecting',CloseDate = System.Today());
        insert opp;
       
        Product2 newProd = new Product2(Name = 'test product', family = 'test family');
         insert newProd;

         PriceBookEntry pbEntry = new PriceBookEntry(
        UnitPrice = 300,
        PriceBook2Id = [select id from PriceBook2 where isStandard = true].Id,
        Product2Id = newProd.Id,
        IsActive = true
    );

    insert pbEntry ;

    Opportunity obj1 = new Opportunity(Name='Test Demo Opportunity', StageName='Lead', CloseDate=Date.today(), Pricebook2Id=pbEntry.PriceBook2Id);   
    insert obj1;

    OpportunityLineItem oli = new OpportunityLineItem(pricebookentryid=pbEntry.Id, Quantity=1, OpportunityId=obj1.id, TotalPrice=1000);
    
      ProductGroup__c ObjProductgroup = new ProductGroup__c(Name=' PG1');
      Insert ObjProductgroup;
      
      Question__c  objquest1 = new Question__c(Name= 'Question1',ProductGroup__c=ObjProductgroup.Id, QuestionText__c='how are you', QuestionType__c='Text');
      Insert objquest1;
      Question__c  objquest2 = new Question__c(Name= 'Question2',ProductGroup__c=ObjProductgroup.Id, QuestionText__c='Will you come out', QuestionType__c='Boolean');
      Insert objquest2;
      Question__c  objquest3 = new Question__c(Name= 'Question3',ProductGroup__c=ObjProductgroup.Id, QuestionText__c='what is your fav color', QuestionType__c='Picklist');
      Insert objquest3;
      
      Answer__c objanswer1 = new Answer__c(Name='Answer1', Opportunity__c= 'opp.Id', Product__c='newProd.Id', Question__c='objquest1.Id');
      Insert objanswer1;
       Answer__c objanswer2 = new Answer__c(Name='Answer1', Opportunity__c= 'opp.Id', Product__c='newProd.Id', Question__c='objquest2.Id');
      Insert objanswer2;
       Answer__c objanswer3 = new Answer__c(Name='Answer1', Opportunity__c= 'opp.Id', Product__c='newProd.Id', Question__c='objquest3.Id');
      Insert objanswer3;
       
    }
}